import Vue from 'vue'
import Router from 'vue-router'
Vue.use(Router)
export default new Router({
    routes:[
        {
            path:'/',
            component:()=>import('../view/student/index')
        },
        {
            path:'/classRoom',
            component:()=>import('../view/student/classRoom')
        },
        {
            path:'/class',
            component:()=>import('../view/student/intoClass/index.vue')
        },
        {
            path:'/homework',
            component:()=>import('../view/student/intoClass/submitWork.vue'),
            children:[
                {
                    path:'submit',
                    alias:'/submit',
                    component:()=>import('../view/student/intoClass/homeWork/submit.vue')
                },
                {
                    path:'watchVideo',
                    alias:'/watchVideo',
                    component:()=>import('../view/student/intoClass/homeWork/watchVideo.vue')
                },
                {
                    path:'viewJob',
                    alias:'/viewJob',
                    component:()=>import('../view/student/intoClass/homeWork/viewJob.vue')
                }
            ]
        },
        {
            path:'/scoreIndex',
            component:()=>import('../view/student/intoClass/score/index.vue'),
            children:[
                {
                    path:'/score',
                    component:()=>import('../view/student/intoClass/score/scores/score.vue'),
                    children:[
                        {
                            path:'homework',
                            name:'homework',
                            component:()=>import('../view/student/intoClass/score/scores/homeworkScore.vue')
                        },
                        {
                            path:'test',
                            name:'test',
                            component:()=>import('../view/student/intoClass/score/scores/testScore.vue')
                        },
                        {
                            path:'classPerformance',
                            name:'classPerformance',
                            component:()=>import('../view/student/intoClass/score/scores/classScore.vue')
                        },
                        {
                            path:'final',
                            name:'final',
                            component:()=>import('../view/student/intoClass/score/scores/finalScore.vue')
                        },
                        {
                            path:'termReview',
                            name:'termReview',
                            component:()=>import('../view/student/intoClass/score/scores/termReviewScore.vue')
                        }
                    ]
                }
            ]
        },
        {
            path:'/students',
            component:()=>import('../view/student/intoClass/score/stuPeople/people.vue')
        },
        {
            path:'/stuPerformance',
            component:()=>import('../view/student/intoClass/stuPerformance/performance.vue')
        },
        {
            path:'/jobPerformance',
            component:()=>import('../view/student/intoClass/jobPerformance/jobPerformance.vue')
        },
        {
            path:'/testPerformance',
            component:()=>import('../view/student/intoClass/testPerformance/testPerformance.vue')
        },
        {
            path:'/testing',
            name:'testing',
            component:()=>import('../view/student/intoClass/testPerformance/testing.vue')
        },
        {
            path:'/evaluation',
            component:()=>import('../view/student/intoClass/teacherEvaluation/evaluation.vue')
        },
        {
            path:'/material',
            component:()=>import('../view/student/intoClass/material/material.vue')
        },
        {
            path:'/materialDetail',
            component:()=>import('../view/student/intoClass/material/materialDetail.vue')
        },
        {
            path:'/notice',
            component:()=>import('../view/student/intoClass/notice/notice.vue')
        },
        {
            path:'/noticeDetail',
            component:()=>import('../view/student/intoClass/notice/noticeDetail.vue')
        },
        {
            path:'/luckDrawIndex',
            component:()=>import('../view/student/intoClass/luckDraw/index.vue'),
            children:[
                {
                    path:'/luckDraw',
                    component:()=>import('../view/student/intoClass/luckDraw/luckDraw.vue')
                },
                {
                    path:'/draw/:id',
                    component:()=>import('../view/student/intoClass/luckDraw/draw.vue')
                }
            ]
        },
        {
            path:'/errorSubject',
            component:()=>import('../view/student/intoClass/errorSubject/error.vue')
        }
    ]
})